library(pwr)
library(effectsize)
data <- read.csv("reaction_times.csv")
head(data)
reaction_time <- t.test(data$AfterTime, mu= 50)
print(reaction_time)
length(data$AfterTime)
d <- cohens_d(data$AfterTime)
effect <- pwr.t.test(n = 25, d = 10.10, sig.level = 0.05, power = NULL, type = "one.sample")
print(effect)
gender <- t.test(data$AfterTime ~ data$Gender, data = data)
print(gender)
effect_2 <- cohens_d(gender)
print(effect_2)
result <- pwr.t.test(d= -0.36, sig.level = 0.05, power = 0.8, type = "two.sample")
print(result)

