student_performance <- read.csv("student_performance.csv")
library(lsr)
mean(student_performance$age)
mean(student_performance$age[1:5])
mean(student_performance$age)
median(student_performance$age)
mode(student_performance$age)
modeOf(student_performance$age)
range(student_performance$gpa, na.rm = TRUE)
max(student_performance$gpa, na.rm = TRUE)
min(student_performance$gpa, na.rm = TRUE)
4.5 - 2.06
range(student_performance$gpa, na.rm = TRUE)
var(student_performance$gpa, na.rm = TRUE)
sd(student_performance$gpa, na.rm = TRUE)
skewness(student_performance$study_hours, na.rm = TRUE)
install.packages("moments")
skewness(student_performance$study_hours, na.rm = TRUE)
plot(student_performance$study_hours, na.rm = TRUE)
hist(student_performance$study_hours)
kurtosis(student_performance$study_hours, na.rm = TRUE)
mean(student_performance$sat_math)
sd(student_performance$sat_math)
593.86 / 115.4606
mean(student_performance$sat_verbal)
sd(student_performance$sat_verbal)
616.04 / 108.6813
hist(student_performance$age)
max(student_performance$age)
min(student_performance$sat_math)
mean(student_performance$age)
median(student_performance$age)
mode(student_performance$age)
modeOf(student_performance$age)
